org: neverendingqs

tokens:
  - repository: serverless-dotenv-example
    permissions:
      contents: write
      pull_requests: write

  - repository: serverless-dotenv-plugin
    permissions:
      contents: write
      pull_requests: write
